In [1]:
import xarray as xr
import rioxarray
import numpy as np
import pandas as pd
from faninsar import Pairs

In [2]:
dates = pd.date_range("20130101", "20231231").values
n = len(dates)
pair_ls = []
for i in range(500):
    np.random.seed(i)
    pair_ls.append(dates[np.random.randint(0, n, 2)])
pairs = Pairs(pair_ls)
pairs

         Pairs
       primary  secondary
0   2013-01-01 2015-03-21
1   2013-01-04 2018-12-13
2   2013-01-06 2013-11-10
3   2013-01-17 2023-02-22
4   2013-01-20 2021-08-22
..         ...        ...
495 2022-11-12 2023-02-01
496 2022-12-26 2023-06-19
497 2023-01-06 2023-09-21
498 2023-03-17 2023-03-22
499 2023-06-12 2023-09-22

[500 rows x 2 columns]

In [3]:
pairs.primary

Acquisition(['2013-01-01', '2013-01-04', '2013-01-06', '2013-01-17',
             '2013-01-20', '2013-02-10', '2013-02-12', '2013-02-17',
             '2013-02-26', '2013-02-28',
             ...
             '2022-05-31', '2022-07-01', '2022-07-22', '2022-08-30',
             '2022-10-08', '2022-11-12', '2022-12-26', '2023-01-06',
             '2023-03-17', '2023-06-12'],
            dtype='datetime64[s]', length=500, freq=None)

In [4]:
con = (pairs.primary.month.map(lambda x: x in [7,8,9])
       & pairs.secondary.month.map(lambda x: x in [7,8,9]))
pairs_summer = pairs[con]

In [5]:
pairs_summer.primary

Acquisition(['2013-08-07', '2013-08-20', '2013-09-20', '2014-07-09',
             '2014-07-16', '2014-07-25', '2014-08-08', '2014-08-19',
             '2014-08-31', '2014-09-14', '2014-09-22', '2014-09-22',
             '2015-07-17', '2016-08-07', '2016-08-21', '2016-09-03',
             '2017-07-01', '2017-07-09', '2017-09-14', '2017-09-26',
             '2018-07-02', '2018-07-05', '2018-07-10', '2018-07-30',
             '2019-07-15', '2019-08-20', '2020-07-15', '2020-08-15',
             '2020-08-24', '2020-09-13', '2021-09-10', '2022-07-01',
             '2022-07-22'],
            dtype='datetime64[s]', freq=None)

In [6]:
pairs

         Pairs
       primary  secondary
0   2013-01-01 2015-03-21
1   2013-01-04 2018-12-13
2   2013-01-06 2013-11-10
3   2013-01-17 2023-02-22
4   2013-01-20 2021-08-22
..         ...        ...
495 2022-11-12 2023-02-01
496 2022-12-26 2023-06-19
497 2023-01-06 2023-09-21
498 2023-03-17 2023-03-22
499 2023-06-12 2023-09-22

[500 rows x 2 columns]

In [7]:
import faninsar as fis
pair1 = fis.Pairs(pairs[0].values)

In [12]:
pairs.dates

Acquisition(['2013-01-01', '2013-01-04', '2013-01-06', '2013-01-17',
             '2013-01-20', '2013-02-10', '2013-02-12', '2013-02-17',
             '2013-02-26', '2013-02-28',
             ...
             '2023-10-29', '2023-10-31', '2023-11-02', '2023-11-06',
             '2023-11-25', '2023-12-01', '2023-12-09', '2023-12-12',
             '2023-12-19', '2023-12-28'],
            dtype='datetime64[s]', length=900, freq=None)

In [9]:
pair1.days[0]

809

In [10]:
//

SyntaxError: invalid syntax (411536581.py, line 1)

In [ ]:
pairs.days

DaySpanIndex([ 809, 2169,  308, 3688, 3136, 1429,   80, 3281, 3254, 1752,
              ...
               145,   31,  426,  301,  427,   81,  175,  258,    5,  102],
             dtype='int32', length=500)

In [ ]:
df = pd.IntervalIndex.from_arrays(pairs.primary, pairs.secondary, closed="both")

In [ ]:
pairs.days

DaySpanIndex([ 809, 2169,  308, 3688, 3136, 1429,   80, 3281, 3254, 1752,
              ...
               145,   31,  426,  301,  427,   81,  175,  258,    5,  102],
             dtype='int32', length=500)

In [ ]:
list(pairs.xindexes.values())[0].__class__.__name__

'Acquisition'

In [ ]:
len("Acquisition([2013-01-01, 2013-01-02, 2013-01-03, 2013-")

54

In [ ]:
html_file = "/Volumes/Data/Github/FanInSAR/temp.html"
with open(html_file, "w") as f:
    f.write(pairs._repr_html_())

In [ ]:
df = pairs.to_frame()
df

       primary  secondary  days
0   2013-01-01 2015-03-21   809
1   2013-01-04 2018-12-13  2169
2   2013-01-06 2013-11-10   308
3   2013-01-17 2023-02-22  3688
4   2013-01-20 2021-08-22  3136
..         ...        ...   ...
495 2022-11-12 2023-02-01    81
496 2022-12-26 2023-06-19   175
497 2023-01-06 2023-09-21   258
498 2023-03-17 2023-03-22     5
499 2023-06-12 2023-09-22   102

[500 rows x 3 columns]

In [ ]:
ds_var = pairs.primary.to_xarray().to_variable()

In [ ]:
import xarray as xr
tif_file = "/Volumes/Data/GeoData/RGV/HyP3/S1AA_20141010T053442_20141103T053442_VVP024_INT40_G_ueF_6E3B/S1AA_20141010T053442_20141103T053442_VVP024_INT40_G_ueF_6E3B_amp.tif"
ds = xr.open_dataset(tif_file)

In [ ]:
pairs.primary.to_xarray().to_index()

DatetimeIndex(['2013-01-01', '2013-01-04', '2013-01-06', '2013-01-17',
               '2013-01-20', '2013-02-10', '2013-02-12', '2013-02-17',
               '2013-02-26', '2013-02-28',
               ...
               '2022-05-31', '2022-07-01', '2022-07-22', '2022-08-30',
               '2022-10-08', '2022-11-12', '2022-12-26', '2023-01-06',
               '2023-03-17', '2023-06-12'],
              dtype='datetime64[ns]', name='Acquisition', length=500, freq=None)

In [ ]:
ds_var

<xarray.Variable (Acquisition: 500)> Size: 4kB
array(['2013-01-01T00:00:00.000000000', '2013-01-04T00:00:00.000000000',
       '2013-01-06T00:00:00.000000000', ..., '2023-01-06T00:00:00.000000000',
       '2023-03-17T00:00:00.000000000', '2023-06-12T00:00:00.000000000'],
      dtype='datetime64[ns]')

In [ ]:
ds.variables.items

<bound method Mapping.items of Frozen({'band': <xarray.IndexVariable 'band' (band: 1)> Size: 8B
array([1]), 'x': <xarray.IndexVariable 'x' (x: 7255)> Size: 58kB
array([320280., 320320., 320360., ..., 610360., 610400., 610440.]), 'y': <xarray.IndexVariable 'y' (y: 5825)> Size: 47kB
array([5280440., 5280400., 5280360., ..., 5047560., 5047520., 5047480.]), 'spatial_ref': <xarray.Variable ()> Size: 8B
[1 values with dtype=int64]
Attributes: (12/18)
    crs_wkt:                           PROJCS["WGS 84 / UTM zone 32N",GEOGCS[...
    semi_major_axis:                   6378137.0
    semi_minor_axis:                   6356752.314245179
    inverse_flattening:                298.257223563
    reference_ellipsoid_name:          WGS 84
    longitude_of_prime_meridian:       0.0
    ...                                ...
    longitude_of_central_meridian:     9.0
    false_easting:                     500000.0
    false_northing:                    0.0
    scale_factor_at_central_meridian:  0.9996
    spatial_ref:                       PROJCS["WGS 84 / UTM zone 32N",GEOGCS[...
    GeoTransform:                      320260.0 40.0 0.0 5280460.0 0.0 -40.0, 'band_data': <xarray.Variable (band: 1, y: 5825, x: 7255)> Size: 169MB
[42260375 values with dtype=float32]
Attributes:
    TIFFTAG_SOFTWARE:  Created with GAMMA Software www.gamma-rs.ch data2geoti...
    TIFFTAG_DATETIME:  2024:04:01 16:33:36
    AREA_OR_POINT:     Point})>

In [ ]:
tif_file = "/Volumes/Data/GeoData/RGV/HyP3/S1AA_20141010T053442_20141103T053442_VVP024_INT40_G_ueF_6E3B/S1AA_20141010T053442_20141103T053442_VVP024_INT40_G_ueF_6E3B_amp.tif"

In [ ]:
ds = rioxarray.open_rasterio(tif_file)
ds

<xarray.DataArray (band: 1, y: 5825, x: 7255)> Size: 169MB
[42260375 values with dtype=float32]
Coordinates:
  * band         (band) int64 8B 1
  * x            (x) float64 58kB 3.203e+05 3.203e+05 ... 6.104e+05 6.104e+05
  * y            (y) float64 47kB 5.28e+06 5.28e+06 ... 5.048e+06 5.047e+06
    spatial_ref  int64 8B 0
Attributes:
    TIFFTAG_SOFTWARE:  Created with GAMMA Software www.gamma-rs.ch data2geoti...
    TIFFTAG_DATETIME:  2024:04:01 16:33:36
    AREA_OR_POINT:     Point
    _FillValue:        0.0
    scale_factor:      1.0
    add_offset:        0.0

In [ ]:
indexes = ds.indexes

In [ ]:
indexes._indexes

{'band': Index([1], dtype='int64', name='band'),
 'x': Index([320280.0, 320320.0, 320360.0, 320400.0, 320440.0, 320480.0, 320520.0,
        320560.0, 320600.0, 320640.0,
        ...
        610080.0, 610120.0, 610160.0, 610200.0, 610240.0, 610280.0, 610320.0,
        610360.0, 610400.0, 610440.0],
       dtype='float64', name='x', length=7255),
 'y': Index([5280440.0, 5280400.0, 5280360.0, 5280320.0, 5280280.0, 5280240.0,
        5280200.0, 5280160.0, 5280120.0, 5280080.0,
        ...
        5047840.0, 5047800.0, 5047760.0, 5047720.0, 5047680.0, 5047640.0,
        5047600.0, 5047560.0, 5047520.0, 5047480.0],
       dtype='float64', name='y', length=5825)}

In [ ]:
ds1 = ds.to_dataset(name="test")

In [ ]:
ds1.xindexes.dims

Frozen({'band': 1, 'x': 7255, 'y': 5825})

In [ ]:
type(ds1.variables)

xarray.core.utils.Frozen

In [ ]:
type(ds1.coords)

xarray.core.coordinates.DatasetCoordinates

In [ ]:
ds_chunk = ds.chunk({"x": 1000, "y": 1000})
ds_chunk

<xarray.DataArray (band: 1, y: 5825, x: 7255)> Size: 169MB
dask.array<xarray-<this-array>, shape=(1, 5825, 7255), dtype=float32, chunksize=(1, 1000, 1000), chunktype=numpy.ndarray>
Coordinates:
  * band         (band) int64 8B 1
  * x            (x) float64 58kB 3.203e+05 3.203e+05 ... 6.104e+05 6.104e+05
  * y            (y) float64 47kB 5.28e+06 5.28e+06 ... 5.048e+06 5.047e+06
    spatial_ref  int64 8B 0
Attributes:
    TIFFTAG_SOFTWARE:  Created with GAMMA Software www.gamma-rs.ch data2geoti...
    TIFFTAG_DATETIME:  2024:04:01 16:33:36
    AREA_OR_POINT:     Point
    _FillValue:        0.0
    scale_factor:      1.0
    add_offset:        0.0

In [ ]:
html_file = "/Volumes/Data/Github/FanInSAR/temp_dask.html"

with open(html_file, "w") as f:
    f.write(ds_chunk._repr_html_())

In [ ]:
from dominate.tags import body, html, p, style

# 创建一个 HTML 文档
doc = html()
with doc.add(body()):
    # 添加样式
    with style(type="text/css"):
        print("""
        [data-after]::after {
          content: attr(data-after);
        }
        """)
    # 创建一个段落元素
    paragraph = p("这是一个段落。")
    # 添加内联样式
    paragraph['style'] = "color: red;"
    # 添加 ::after 伪元素的样式
    paragraph['data-after'] = "content: ' ::after 内容'; color: blue;"

# 打印生成的 HTML
print(doc)

        [data-after]::after {
          content: attr(data-after);
        }

<html>
  <body>
    <style type="text/css"></style>
    <p data-after="content: ' ::after 内容'; color: blue;" style="color: red;">这是一个段落。</p>
  </body>
</html>